[package]
name = "smart-meter-server"
version = "0.1.0"
authors = ["Sam Parkinson <sam@sam.today>"]

[dependencies]
rocket = "0.3.16"
rocket_codegen = "0.3.16"
rocket_contrib = "0.3.16"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
influent = "0.4"
